apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    service: 80
    targetPort: 80
  